### ISSUE TITLE
When execute Ridgepole with `--diff` option, migration is running

### ISSUE THREAD

**Issue by mi-wada** [ridgepole/ridgepole#499] opened 2024-08-21 11:02 UTC
# Version

* Ridgepole: 2.1.0
* Ruby: 3.3.0
* Rails/Active Record: 7.1.3.4
* MySQL/PostgreSQL: MySQL 5.7
* MySQL adapter: trilogy 2.8.1

# Description

(Maybe) Bug report

It seems that running Ridgepole with the `--diff` option (without `--with-apply`) is executing migrations.

From what I understood by reading the [README](https://github.com/ridgepole/ridgepole?tab=readme-ov-file#diff), the expected behavior is that migrations should be executed only when `--with-apply` is specified, and not when it isn't.
(If this behavior is intentional, please close this issue.)

```shell
$ bundle exec rails runner "puts ActiveRecord::Base.connection.columns('users').map(&:name)"
Running via Spring preloader in process 11227
id
name

$ bundle exec ridgepole --diff Schemafile.before Schemafile.after
add_column("users", "email", :string, **{:after=>"name", :limit=>255})

$ bundle exec rails runner "puts ActiveRecord::Base.connection.columns('users').map(&:name)"
Running via Spring preloader in process 11724
id
name
email
```

# Schemafile

`Schemafile.before`
```rb
create_table(:users) do |t|
  t.string :name
end
```

`Schemafile.after`
```rb
create_table(:users) do |t|
  t.string :name
  t.string :email
end
```

# DDL

# Export

# Apply with `--verbose`

**Comment by winebarrel** [comment] 2024-09-29 02:02
I can't reproduce the problem in my environment, can you please provide me with the following information?

- Actual DDL of the table
- Export result (`ridgepole -e`)
- `--diff` wih `--verbose` option
cf.

![スクリーンショット 2024-09-29 11 02 09](https://github.com/user-attachments/assets/6760d7f3-33b6-4ada-a3b3-6d55b200ee25)

**Comment by winebarrel** [comment] 2024-11-04 02:43
I have no reply so I have closed it.
Thanks for the issue.

**Closed by winebarrel** 2024-11-04 02:43 UTC
